### ISSUE TITLE
Can't load mod

### ISSUE THREAD

**Issue by MeongMeongMeong** [SoliaRdi/PacketsLogger#2]
It says this
[22:28:12.716] [mods] ERROR: Module "PacketsLogger" (PacketsLogger-master) could not be loaded!
[22:28:12.718] [mods] ERROR: Please contact the module's author: https://github.com/SoliaRdi/
[22:28:12.719] { Error: Cannot find module 'hexy'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (D:\Tera Proxy\Testing\CaaliTeraProxy\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\Tera Proxy\Testing\CaaliTeraProxy\mods\PacketsLogger-master\index.js:1:169)
    at Object.<anonymous> (D:\Tera Proxy\Testing\CaaliTeraProxy\mods\PacketsLogger-master\index.js:540:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32) code: 'MODULE_NOT_FOUND' }

**Comment by kyogo123** [comment]
I don't know if you still need help but if you go over to the opcodes-4-dummies github made by beng-mods there is a folder there with 'hexy'. You just have to drop that folder into the node_modules in your proxy.

**Comment by MeongMeongMeong** [comment]
oh, isee, thx
