### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by ve3k** [SoliaRdi/PacketsLogger#4]
[mods] ERROR: Module "PacketsLogger" (PacketsLogger-master) could not be loaded!
[mods] ERROR: Please contact the module's author: https://github.com/SoliaRdi/
{ Error: Cannot find module 'hexy'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\Games\caali-proxy\mods\PacketsLogger-master\index.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3) code: 'MODULE_NOT_FOUND' }

**Comment by porkbonesoups** [comment]
you can find hexy [here](https://github.com/beng-mods/opcodes-4-dummies)

**Comment by Patricktheorge** [comment]
how to install hexy T_T
